[package]
name = "aoc2020"
version = "0.1.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "*", features = ["rustls-tls", "gzip", "blocking"] }
config = { version = "*", features = ["toml"] }
clap = "*"

[workspace]
members = [
	"day_1",
]
